### ISSUE TITLE
很好的模板，反馈几点关于参考文献的问题

### ISSUE THREAD

**Issue by wesleyel** [1989Ryan/XJTU-Bachelor-Thesis-LaTeX-Template#3]
很感谢作者提供的本模板，我在使用本模板的过程中也佩服于作者 $\LaTeX$ 功力之深。

关于参考文献的问题如下：

1. 默认情况下使用`biber`命令对`.bib`文件格式化时，会将`journal`条目重命名为`journaltitle`. 由于`xjtuthesis-numerical.bst`中没有关于`journaltitle`的ENTRY以及处理的相关FUNCTION，所以输出的参考文献中会缺少journal来源。

```
biber --tool --output_align --output_indent=2 --output_fieldcase=lower bib/mybib.bib
```

2. `xjtuthesis-numerical.bst`中处理`article`年份时，应使用`format.year`函数。
```
FUNCTION {article}
{ 
%% ...
  format.date "year" output.check  -->  format.year "year" output.check
%% ...
}
```
否则会提示 `date is empty`。

**Comment by wesleyel** [comment]
我尝试了解决这个问题，并提交了一个PR（#4 ）

以下是前后对比，杂志名和日期有一些变化。
![image](https://user-images.githubusercontent.com/48174882/173173331-fd291958-67e0-4c22-a179-e1684aae32a3.png)
![image](https://user-images.githubusercontent.com/48174882/173173384-e13ff4aa-80dc-4835-b90e-0419eb864fbe.png)

**Comment by 1989Ryan** [comment]
收到，谢谢你的肯定，也非常感谢你的贡献！

**Comment by wesleyel** [comment]
❤️
